### ISSUE TITLE
Register an account

### ISSUE THREAD

**Issue by Oluwapelumi99** [Oluwapelumi99/Cuppy-s-restaurant#1]
As a **User**, I would like **to  be able to register an account**, so that **I can make a booking **

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given**  that I am a user
    **When**  I provide my email
    **Then** I can register and make a booking
-	Acceptance Criteria 2
    **Given** that I am a registered user
    **When**   I use the login button
    **Then**  I can log in to my account and view my booking
-	Acceptance Criteria 3
    **Given** that I am a registered user
	And, I try to log in to my account
    **When** I enter the wrong information
    **Then** the site informs me that the information was incorrect and prevents my logging in

### Tasks
-	[] Task 1 – Develop a registration page
-	[] Task 2 – Develop a log in link and form
-	[] Task 3 – Develop form validation to ensure the data is entered correctly
-	[] Task 4 – Develop a method to validate the data entered matches a user account
